### ISSUE TITLE
Manipulated images with anki-resize-image are distorted in Ankidroid

### ISSUE THREAD

**Issue by Farinata** [Arthur-Milchior/anki-resize-image#16]
Dear arthur thanks for the addon

I have a big issue. I have manipulated hundreds of images with this addon, but recently noticed these images are completely distorted (elongated) and unreadable in Ankidroid. When I disabled the addon and added new images they are ok and fine. Previous added images before the addon are fine. However, even after I disabled the addon the manipulated images are still distorted in the Ankidroid!

Please help as I manipulated about 1000 images

This is my current card  styling

```css
html { overflow: scroll; overflow-x: hidden; }
/* CONTAINER FOR YOUR CARDS */
#kard {
padding: 0px 0px;
max-width: 700px; /* CHANGE CARD SIZE HERE */
margin: 0 auto; /* CENTERS THE CARD IN THE MIDDLE OF THE WINDOW */
word-wrap: break-word; /* BREAKS UP LONG WORKS */
}

/* APPLIES TO THE WHOLE CARD */
.card {
font-family: arial, baskerville, sans;
font-size: 24px; /* FONT SIZE */
text-align: center; /* ALIGN TEXT */
color: #D7DEE9; /* FONT COLOR */
line-height: 1.6em;
background-color: #333B45; /* BACKGROUND COLOR */
}
/* STYLE FOR CLOZE DELETIONS */
.cloze, .cloze b, .cloze u, .cloze i { font-weight: bold; color: MediumSeaGreen !important;}

/* STYLE FOR EXTRA PORTION ON BACK OF CARD */
#extra, #extra i { font-size: 22px; color:orange; font-style: italic; }

/* STYLE TAGS TO APPEAR WHEN HOVERING OVER TOP OF CARD */
.tags { 
    color: #A6ABB9;
    opacity: 0;
    font-size: 12px; 
    width: 100%;
    text-align: center;
    text-transform: uppercase; 
    position: fixed; 
    padding: 0; 
    top:0;  
    right: 0;}
.tags:hover { opacity: 1; position: fixed;}

/* IMAGE STYLE */
img { display: block; max-width: 100%; max-height: none; margin-left: auto; margin: 10px auto 10px auto;}
tr {font-size: 12px; }


/* ADJUSTMENT FOR MOBILE DEVICES */
.mobile .card { color: #D7DEE9; background-color: #333B45; } 
.mobile .tags:hover { opacity: 1; position: relative;}

/* COLOR ACCENTS FOR BOLD-ITALICS-UNDERLINE */
b { color: #C695C6 !important; } /* BOLD STYLE */
u { text-decoration: none; color: #5EB3B3;} /* UNDERLINE STYLE */
i { color: IndianRed; } /* ITALICS STYLE */
a { color: LightGray !important; text-decoration: none; font-size: 10px; font-style: normal; } /* LINK STYLE */


/*FOR THE HINT PANEL*/
a {
color: lightgreen;
text-decoration: inherit;
font-size: 16px;
}
```

Addon configuration (I didn't change anything)

``` json
{
    "0": 0,
    "apply maximum height when not resizing": false,
    "apply maximum width when not resizing": false,
    "apply minimum height": true,
    "apply minimum height when not resizing": true,
    "apply minimum width": true,
    "apply minimum width when not resizing": true,
    "image-classes": [],
    "max-height": 200,
    "max-width": 200,
    "min-height": 10,
    "min-width": 10,
    "preserve ratio while resizing": "current",
    "resizable-style": "border:1px dashed black;"
}

This is a reddit link with images
[https://www.reddit.com/r/medicalschoolanki/comments/fz1d0k/problems_with_ankidroid_images/](url)

I attached as you requested one extracted card (the images in this card were manipulated with the addon and appear elongated and distorted on Ankidroid (but fine in Anki desktop)
[Selected Notes.zip](https://github.com/Arthur-Milchior/anki-resize-image/files/4465443/Selected.Notes.zip)
